name: GTFS ETL Process

on:
  push:
    branches:
      - main ## added this to invoke new commit
  workflow_dispatch:
    # Adding inputs for manual triggering with optional parameters
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: false
        default: 'Scheduled run via Google Cloud Scheduler'
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      scheduler_job_id:
        description: 'Google Cloud Scheduler job ID (for tracking)'
        required: false
        default: 'default-scheduler'
      execution_time:
        description: 'Scheduled execution time (UTC)'
        required: false
        default: ''

# Removed concurrency configuration entirely to prevent any cancellation issues

jobs:
  run-etl:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Log workflow trigger information
        id: log-info
        run: |
          echo "Workflow triggered at: $(date -u)"
          echo "Trigger reason: ${{ github.event.inputs.reason || 'Push to main branch' }}"
          echo "Debug mode: ${{ github.event.inputs.debug_mode || 'false' }}"
          echo "Scheduler job ID: ${{ github.event.inputs.scheduler_job_id || 'N/A' }}"
          echo "Scheduled execution time: ${{ github.event.inputs.execution_time || 'N/A' }}"
          echo "GitHub run ID: ${{ github.run_id }}"
          echo "GitHub run number: ${{ github.run_number }}"
          echo "Workflow dispatch event ID: ${{ github.event.id || 'N/A' }}"
      
      - name: Run GTFS ETL process
        id: run-etl
        env:
          LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT || '6379' }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_DB: ${{ secrets.REDIS_DB || '0' }}
          REDIS_EXPIRY_HOURS: '12'
          DEBUG_MODE: ${{ github.event.inputs.debug_mode || 'false' }}
          SCHEDULER_JOB_ID: ${{ github.event.inputs.scheduler_job_id || 'default-scheduler' }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          start_time=$(date +%s)
          python gtfs_stops.py
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "duration=$duration" >> $GITHUB_OUTPUT
      
      - name: Report job status
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "ETL process completed successfully"
            echo "Run duration: ${{ steps.run-etl.outputs.duration || 'N/A' }} seconds"
          else
            echo "ETL process failed"
            echo "See logs for details"
          fi 